### ISSUE TITLE
[2021 fall] ECCV 2020 End-to-end Object Detection with Transformers (20214239)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#103]

**Comment by povolann** [comment]
Hi, I'm Anna Povolna (20205678) and here is my comment on your review.

### **Overall Review**

- Please, correct the rendering of images and mathematical equations.
- "Take-home lesson" section is missing.
- There are many grammar mistakes.
- It's hard to understand what the author wanted to say in a few instances (see **Consider rewriting these parts** section).
- I appreciate that the author tried to write the review in a common language, avoiding academic language, so it is easier to read and understand.
- The author doesn't metion that DETR is fully differentiable which is quite important contribution, in my opinion.

#### **Common grammar mistakes**

- In some cases, it doesn't make sense to start a sentence with "and".
- No comma before "if".
- Check the commas in sentences.
- Wrong using of tense for verbs.

#### **Consider rewriting these parts**
Here, I have higlighted some parts of the review which are not quite clear. Please, consider rewriting them.

- _So a problem always arises with this, and this issue is that the image_
   - unecessary long.
- _They also have a powerful feature that inspired which mainly what inspired the authors of DETR to use them. This feature is the transformers have what is called attention blocks._ 
   - maybe something like: "The transformers have a powerful feature called attention blocks which inspired the authors of DETR to use the transformers."
- _DETR can global reason about the final set of predicted bounding boxes._
   - I'm not sure what the author tried to say with this.

**Comment by sateodoro** [comment]
Hello! I am Samuel Teodoro (20218258) and here are my comments:

1. The images/figures are not loading properly.
2. Figures are not properly accompanied by their corresponding figure titles.
3. Equations are not properly presented.
4. There are plenty spelling, grammar, and punctuation mistakes.
5. In section 2.2, I think the word "gazillion" should be replaced with, for example, countless, as the former is too informal.
6. Panoptic segmentation was mentioned in Section IV. It is probably better for the readers if you give a brief background about (or define) panoptic segmentation.
7. There is no Take Home Message.
