### ISSUE TITLE
[2021 fall] MICCAI 2021 Dual-Domain Adaptive-Scaling Non-Local Network for CT Metal Artifact Reduction (20205678)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#105]

**Comment by Seung-HO-HAN** [comment]
1. Equations should be covered with " "
2. Images are not shown. Please follow the file directory structure introduced in awesome review guidline. 
3. Typically, X-ray image has 1000 x 1000 size and CT image is bigger than this. Please check your conclusion part.

**Comment by Errors-Everywhere** [comment]
Hi, I'm Ahmed Magd (20214239). I really enjoyed reading your review.

Please consider these minor comments that I have:

- Images are not displayed
- Mathematical expressions that are in-between sentences are not displayed properly as well.
-  **(Suggestion)** Try to use short sentences instead of long ones if possible. Also, consider using commas if you have to use long sentences.
  - **Example:** A novel residual sinogram learning strategy is proposed to avoid transforming two different data distributions into a uniform one and to improve the smoothness of the corrected projection.
- There are some mistakes (typos) as in:
  - state of art methods -> state-of-the-art methods
  - proove -> prove (not sure if you wrote it like this intentionally or by mistake)

Also, please check the comments that I have included in the attached file:
[DAN_Net_Review.pdf](https://github.com/awesome-davian/awesome-reviews-kaist/files/7532415/DAN_Net_Review.pdf)
