### ISSUE TITLE
[2021 fall] CVPR 2021 UPFlow - Upsampling Pyramid for Unsupervised Optical Flow Learning (20214574)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#133]

**Comment by fxnnxc** [comment]
It is a review of review #3 박범진

(I wrote in English because your article is written in English)

This article explains UpFlow model and the introduction and motivation of the paper are written well. 

**Comments**

1. There should be a description about the function F_{t}^{4} in Figure 6 and other mathematical notations ( S and s_downarrow in figure 10) 

2. It will be nicer if there is a detailed explanation about the red and blue region in Figure 7. (**what are red and blue regions?**)

3. Please use $$V_{vest}$$ in the Evaluation metric and also other mathematical notations.  

4. **Figure 10 ** → `**Figure 10** `

**Comment by IamHanJungMin** [comment]
좋은 논문 리뷰 잘 읽었습니다. 감사합니다.
아래 코멘트를 남겨 드리오니 업데이트에 참고 부탁 드립니다.

- Problem Definition 섹션에서 Upsampling이 어떤 분야이고, 어디에 활용될 수 있는지를 추가적으로 간단히 설명해주신다면 이 분야가 아직 익숙하지 않은 독자들에게 많은 도움이 될 것 같습니다.
- 본 논문의 저술 의도에 대해 이야기 할 때, Abstract 의 내용을 일부 참고하시면 내용 전달이 더 잘될 것 같습니다.
- 본문에 삽입된 각 Figure나 Table에 번호나 제목이 추가되면 좋을 것 같습니다. 내용을 논문에서 발췌하셨다면 관심있는 독자들을 위해 논문에서 나온 제목을 그대로 가져다 쓰셔도 좋을 것 같습니다.
- 독자들의 원리에 대한 이해를 돕기 위해 Reference & Additional materials 부분에 본 논문에 대한 발표 동영상을 링크해도 좋을 것 같습니다. 링크는 아래를 참조 부탁 드립니다.
  https://www.youtube.com/watch?v=voD3tA8q-lk

**Comment by heyzude** [comment]
안녕하세요, 리뷰 잘 읽었습니다.
아래 사항들은 제가 느낀 것들인데 참고하면 감사하겠습니다.
* UFlow3, UnFlow4 부분 그림들을 확대하면 좋겠습니다.
* Interpolation flow가 무엇인지 정의가 뭔지 모르겠습니다.
* Interpolation flow와 interpolation map 간의 차이가 무엇인지요
* 논문에서 원본 이미지를 Smaller resolution으로 encoding하는 방법과, V_f를 downsampling 하는 방법으로는 어떤 방법을 사용했나요?
* (제가 unsupervised learning 방법에 대해 잘 몰라서일수도 있습니다만) Pyramid Distillation Loss Ld in **Figure 10 **uses the the final output optical flow Vf as pseudo labels --> 도출된 final output optical flow V_f는 모델의 output인걸로 알고 있습니다 (Ground-truth optical flow가 아닌). V_f가 맞는지 안 맞는지 알지 않고도 전체적인 러닝을 잘 할수 있나요?
