### ISSUE TITLE
[2021 fall] CVPR 2021 Right for the Right Concept: Revising Neuro-Symbolic Concepts by Interacting with their Explanations (20204363)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#154]

**Comment by indigopyj** [comment]
안녕하세요, 저는 카이스트 AI대학원 석사과정 박여정입니다.

1. 수식은 $x$가 아니라 $$x$$ 이렇게 해야 인코딩됩니다.
2. 이미지 크기가 더 크면 보기 좋을것 같습니다.
3. method의 내용이 좀 더 자세하면 좋을 것 같습니다. 예를 들면 도트형태가 있는 도표들은 어떤걸 의미하는지..이 분야에 대해 생소한 저로써는 그림 자체를 이해하기가 힘드네요. 그리고 visual explainer를 통해 나온 아웃풋은 뭘 의미하고 있는지도 설명해주시면 좋겠습니다.
4. "Clever-Hans와 같은 순간을 겪고 있는 것을 보여줍니다." 이게 무슨 의미일까요? 비슷한 현상을 나타내고 있다는 것일까요?
5. 결론에서 "CLEVER-Hans3과 CLEVER-Hans7을 구축했다"라고 하고 있는데, 이 데이터셋에 대한 내용이 없네요.

전반적으로 리뷰 앞부분은 흥미롭게 읽었는데요, 모델구조를 이해하기가 힘들어서 읽는데 애를 먹었습니다. 그래도 리뷰 잘 읽었습니다.

**Comment by povolann** [comment]
Hi, I'm Anna Povolna (20205678) and here is my comment on your review.

### **Overall Review**

- Link to the Korean version of this review is missing.
- Please, correct the rendering of mathematical equations.
- "Reference & Additional materials" section is missing.
- There are some grammar mistakes. Especially when the author of the review was rewriting something from the original paper, but didn't look at the context of that particular sentence - in some cases you need to change the wording, tense, etc. Some examples are in **Common grammar mistakes** section.
- It's hard to understand what the author wanted to say in a few instances (see **Consider rewriting these parts** section).
- I think that it would be nice to describe both datasets (CLEVER-Hans3 and CLEVER-Hans7) since they are also part of the paper's contribution.

#### **Common grammar mistakes**

- Wrong using of tense for verbs.
   - _The architecture consisting of two modules..._ -> "The architecture consists of two modules..."
   - _Using additional explanatory loss, we intervenes on the model's behavior._ -> "Using additional explanatory loss, we intervene in the model's behavior."
- typo in "Conclusion" - _using "visual" expalantions only_ -> "using "visual" explanations only"
- Check articles before nouns.
- Check commas in sentences.

#### **Consider rewriting these parts**
Here, I have highlighted some parts of the review which are not quite clear. Please, consider rewriting them.

- _These "visual" explanations do not provide semantic explanations of how the model determines._
   - It seems like part of the sentence is missing - the model determines what?
- _In the case of the concept module, it plays a role in mapping into symbolic expressions that humans can understand._
   - "It" is referring to what exactly? Does the concept module play a role or the architecture? It is not clear.
- _Given these two modules, we can extract explanations for the separate tasks,_
   - Which tasks?

**Comment by pranjay-unof** [comment]
Hello, I am Pranjay Shyam (20185586) the reviewer assigned for this paper review. 

I would like to summarize the areas of revision for the English review as,

- Figures and Tables can be enlarged along with its caption to improve the readability. 
- There are some typos in the paper that can be corrected. 
- The equations are not being rendered correctly.
- Reference & Additional materials are missing
- The dataset summary as referred in Paper in Table 1 can be used instead in Dataset subsection.
- Mathematical Expression of calculation for evaluation metrics can be beneficial for readers. 
- Examples from the CLEVR-Hans3 dataset  can be provided, eg. Figure 4 from the paper.
- Some portions within the review are kept open in the method section
