### ISSUE TITLE
[2021 fall] CVPR 2021 Multiple Instance Active Learning for Object Detection (20215414)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#161]

**Comment by madin162** [comment]
Hello, this is Muhammad Adi, and I would like to give some feed backs for your article.
Overall I really enjoy reading it because of its completeness and orderly structure.
The motivation, related works, and method explanation are written well so that I, as the reader, can understand the topic much easier.
I also find the conclusion and your views on the paper strengths and weakness pretty cool.

To make it even better, here are some minor improvements I suggested:
1. The size for some important figure can be readjusted, such as Figure 11.
2. Some minor improvement on typing can be made, e.g. correction on numbering for Model Analysis and typo in "satistical analysis".

**Comment by Errors-Everywhere** [comment]
Hi, I'm Ahmed Magd (20214239). First of all, I really loved your review and enjoyed reading it. Also I salute you for choosing this interesting paper to review.

Now to the feedback. As I said the review was well written in my opinion; however, I have the following minor comments:

- Some figures appear to be smaller than what they should be (this is in the gitbook article).
- Check the notation of the unlabeled data in the “Formal Definition” section. Because it is not visible in the article.
- Consider writing the equations and tables instead of using images to represent them. This will make article more appealing to the readers (in my opinion). (as you can see, some tables appear to be huge while others are smaller, but if you wrote the tables yourselves, they will appear in a more natural way)
- Finally please take a look at the attached file. It has some comments about some typos, grammatical mistakes or phrases that I think need to be rephrased. (We all have similar mistakes. In my paper review I have so many mistakes like this, but it is better to point them out, so that we can fix them later)
[MI-AOD.pdf](https://github.com/awesome-davian/awesome-reviews-kaist/files/7533488/MI-AOD.pdf)

**Comment by tungnt101294** [comment]
Thanks for the review, Muhammad @madin162 and Admed @Errors-Everywhere. I will try to review and notify you guys once I'm done.
